
#Pour la production

spring:
  application:
    name: DeptManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_DATASOURCE_PASSWORD}
    username: ${JDBC_DATASOURCE_USERNAME}
    password: ${JDBC_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
